person:
  last-name: wangxqdev_${random.uuid}
  age: ${random.int}
  boss: true
  birthday: 1989/2/22 17:01:00
  demo-map: { k1: v1, k2: 18 }
  demo-list:
    - zhangsan
    - lisi
    - wangwu
  dog:
#    ${属性名:默认值}
    name: ${person.hello:hello}_dog
    age: 2

cat:
  name: haha

# 1. 启动参数：--spring.profiles.active=
# 2. 虚拟机参数：-Dspring.profiles.active=
# 3. yml片段：---
# 4. application-{profiles}.yml
# 5. 启动参数：--spring.config.location=
spring:
  profiles:
    active: prod